
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 23.5.0 - arm64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "/opt/homebrew/share/cmake/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "/opt/homebrew/share/cmake/Modules/CheckCCompilerFlag.cmake:56 (cmake_check_compiler_flag)"
      - "vendor/raylib/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "vendor/raylib/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "vendor/raylib/CMakeLists.txt:27 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "/Users/aadikulsh/Documents/CProjects/Software Renderer/build-web/CMakeFiles/CMakeScratch/TryCompile-mtAr7a"
      binary: "/Users/aadikulsh/Documents/CProjects/Software Renderer/build-web/CMakeFiles/CMakeScratch/TryCompile-mtAr7a"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/cmake/Modules;/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/cmake/Modules;/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/cmake/Modules;/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/cmake/Modules;/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/cmake/Modules;/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/raylib/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: '/Users/aadikulsh/Documents/CProjects/Software Renderer/build-web/CMakeFiles/CMakeScratch/TryCompile-mtAr7a'
        
        Run Build Command(s): /opt/homebrew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_11eea/fast
        /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_11eea.dir/build.make CMakeFiles/cmTC_11eea.dir/build
        Building C object CMakeFiles/cmTC_11eea.dir/src.c.o
        "/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/emcc" -DCOMPILER_HAS_THOSE_TOGGLES  -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_11eea.dir/src.c.o -MF CMakeFiles/cmTC_11eea.dir/src.c.o.d -o CMakeFiles/cmTC_11eea.dir/src.c.o -c "/Users/aadikulsh/Documents/CProjects/Software Renderer/build-web/CMakeFiles/CMakeScratch/TryCompile-mtAr7a/src.c"
        Linking C executable cmTC_11eea.js
        /opt/homebrew/bin/cmake -E cmake_link_script CMakeFiles/cmTC_11eea.dir/link.txt --verbose=1
        "/Users/aadikulsh/Documents/CProjects/Software Renderer/vendor/emsdk/upstream/emscripten/emcc" @CMakeFiles/cmTC_11eea.dir/objects1.rsp -o cmTC_11eea.js
        
      exitCode: 0
...
